# Generated by Django 5.0 on 2024-05-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='nbr_chambre',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='nbr_salle_bain',
            field=models.IntegerField(blank=True),
        ),
    ]
