# Generated by Django 5.0 on 2024-05-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immo', '0003_alter_property_nbr_chambre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
